### ISSUE TITLE
Favorites ignores the Default File Manager setting

### ISSUE THREAD

**Issue by elvinvandalen** [stax76/Flow.Launcher.Plugin.Favorites#7]
I've set up a different file manager in _General/Default File Manager_. But when I try to open any of the Favorites results, it opens in the default Windows File Explorer. Is this a bug in the plugin or is this a bug in Flow Launcher itself?

**Comment by stax76** [comment]
It's a bug or missing feature in the Favorites plugin.

Personally, for folders in the Favorites plugin, I use a wrapper app:

https://github.com/stax76/command-line-to-exe

command-line-to-exe conf:

```
path = D:\foobar\AutoHotkey\AutoHotkey64.exe
args = D:\foobar\AHK\open-in-explorer.ahk "%1%"
```
In Favorites plugin:

`CS Folder = open-folder D:\Projects\CS`

Autohotkey script:

```
If !WinExist("ahk_class CabinetWClass")
{
	Run "explorer.exe " A_Args[1]
    WinWait "ahk_class CabinetWClass"
    Sleep 500
    Send "{Space}"  ; select first file/folder
}
Else
{
    while GetKeyState("LControl")
    {
        Sleep 50
    }
    WinActivate "ahk_class CabinetWClass"
    Send "^t"  ; send Ctrl+T to create a new tab
    Send "!d"  ; send Alt+d to focus the address bar
    Sleep 500
    Send "{Raw}" Trim(A_Args[1], '"')  ; write folder into address bar
    Sleep 500
    Send "{Enter}"  ; confirm to open folder  
    Sleep 500
    Send "{Space}"  ; select first file/folder
}
```
This in Windows 11 opens new folders in a new explorer tab instead of a new explorer window. The Autohotkey script unfortunately isn't 100 % reliable and in the Favorites plugin, the command line icon is shown instead of the folder icon.

When I have time, I see what I can do.

Which file manager are you using, btw?

**Comment by elvinvandalen** [comment]
Great, thanks for the quick response. I'll have a look at your suggestion.
I'm using [Files](https://files.community/) as a file explorer replacement.
